urls.py
from django.conf.urls import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

book_id = '(?P<book_id>[^/]+)'
case = '(?P<case>[^/]+)'
choice = '(?P<choice>[^/]+)'
comp = '(?P<comp>[^/]+)'
correct = '(?P<correct>[^/]+)'
day = '(?P<day>[^/]+)'
gender = '(?P<gender>[^/]+)'
id = '(?P<id>[^/]+)'
listname = '(?P<listname>[^/]+)'
month = '(?P<month>[^/]+)'
mood = '(?P<mood>[^/]+)'
name = '(?P<name>[^/]+)'
number = '(?P<number>[^/]+)'
ordering = '(?P<ordering>[^/]+)'
page_id = '(?P<page_id>[\d]+)'
page_num = '(?P<page_num>[^/]+)'
person = '(?P<person>[^/]+)'
review_style = '(?P<review_style>[^/]+)'
string = '(?P<string>[^/]+)'
tag = '(?P<tag>[^/]+)'
tense = '(?P<tense>[^/]+)'
user = '(?P<user>[^/]+)'
value = '(?P<value>[^/]+)'
verb_id = '(?P<verb_id>[^/]+)'
voice = '(?P<voice>[^/]+)'
word = '(?P<word>[^/]+)'
word_id = r'(?P<word_id>[\d]+)'
year = '(?P<year>[^/]+)'

urlpatterns = patterns('',
    # The main page is the main list view
    (r'^$',
        'drills.views.lists.main'),
    (r'^logout$',
        'drills.views.common.logout'),

    # Reading urls
    (r'^book/'+book_id+'/$',
        'reading.views.book'),
    (r'^book/'+book_id+'/page/'+page_num+'/$',
        'reading.views.page'),
    (r'^book/'+book_id+'/page/'+page_num+'/edit-chapter$',
        'reading.views.edit_page_chapter'),
    (r'^book/'+book_id+'/page/'+page_num+'/edit-text$',
        'reading.views.edit_page_text'),
    (r'^page-image/'+page_id+'$',
        'reading.views.page_image'),
    (r'^definition/'+word+'$',
        'reading.views.definition'),

    # Extension urls
    (r'^extension/definition/' + user + '/' + listname + '$',
        'drills.views.vocab.get_definition'),
    (r'^extension/read/' + user + '/' + listname + '$',
        'drills.views.vocab.submit_as_read'),

    # Vocab urls
    (r'^'+listname+'/vocab/$',
        'drills.views.vocab.main'),
    (r'^'+listname+'/vocab/next-word/'+correct+'$',
        'drills.views.vocab.next_word'),

    # Vocab (manual) urls
    (r'^'+listname+'/vocab/manual/$',
        'drills.views.vocab_manual.main'),
    (r'^'+listname+'/vocab/manual/add-tag$',
        'drills.views.vocab_manual.add_tag'),
    (r'^'+listname+'/vocab/manual/next-word/$',
        'drills.views.vocab_manual.next_word'),
    (r'^'+listname+'/vocab/manual/next-word/'+correct+'$',
        'drills.views.vocab_manual.next_word'),
    (r'^'+listname+'/vocab/manual/prev-word/$',
        'drills.views.vocab_manual.prev_word'),
    (r'^'+listname+'/vocab/manual/reorder-word-list/'+ordering+'$',
        'drills.views.vocab_manual.reorder_word_list'),
    (r'^'+listname+'/vocab/manual/set-by-definition/'+value+'$',
        'drills.views.vocab_manual.set_by_definition'),

    # Filters and tags
    (r'^'+listname+'/new-filter/'+name+'$',
        'drills.views.filters.add_filter'),
    (r'^remove-filter/'+id+'$',
        'drills.views.filters.remove_filter'),
    (r'^update-one-choice-filter/'+id+'/'+choice+'$',
        'drills.views.filters.update_one_choice_filter'),
    (r'^update-value-comp-filter/'+id+'/'+comp+'/'+value+'$',
        'drills.views.filters.update_value_comp_filter'),
    (r'^update-string-filter/'+id+'/'+string+'$',
        'drills.views.filters.update_string_filter'),
    (r'^update-date-filter/'+id+'/'+comp+'/'+year+'/'+month+'/'+day+'$',
        'drills.views.filters.update_date_filter'),
    (r'^'+listname+'/add-tag-to-word/'+tag+'$',
        'drills.views.common.add_tag_to_word'),
    (r'^'+listname+'/remove-tag-from-word/'+tag+'$',
        'drills.views.common.remove_tag_from_word'),

    # Form drilling urls
    (r'^'+listname+'/forms/$',
        'drills.views.forms.drill_conjugations'),
    (r'^'+listname+'/forms/conjugations$',
        'drills.views.forms.drill_conjugations'),
    (r'^'+listname+'/forms/declensions$',
        'drills.views.forms.drill_declensions'),
    (r'^'+listname+'/get-new-random-form/$',
        'drills.views.forms.get_new_random_form'),
    (r'^'+listname+'/inflect-form/'+person+'/'+number+'/'+tense+'/'+mood+
            '/'+voice+'$',
        'drills.views.forms.inflect_form'),
    (r'^'+listname+'/guess-verb-form/'+person+'/'+number+'/'+tense+'/'+mood+
            '/'+voice+'$',
        'drills.views.forms.guess_verb_form'),
    (r'^'+listname+'/guess-noun-form/'+gender+'/'+number+'/'+case+'$',
        'drills.views.forms.guess_noun_form'),
    (r'^'+listname+'/get-new-verb/'+id+'$',
        'drills.views.forms.get_new_verb'),

    # Form viewing urls
    (r'^'+listname+'/view-forms/$',
        'drills.views.forms.view_forms'),
    (r'^'+listname+'/view-table/'+verb_id+'$',
        'drills.views.forms.view_table'),
    (r'^'+listname+'/view-table/'+verb_id+
            '/update-table/'+person+'/'+number+'$',
        'drills.views.forms.update_table'),

    # List views
    # These are at the bottom because they tend to be matched by other things
    # that really shouldn't match.
    (r'^'+listname+'$',
        'drills.views.lists.single_list'),
    (r'^'+listname+'/add-word$',
        'drills.views.lists.add_word_to_list'),
    (r'^'+listname+'/add-word/add-irregular-noun-form/'+number+'$',
        'drills.views.lists.add_irregular_noun_form'),
    (r'^'+listname+'/add-word/add-irregular-adj-form/'+number+'$',
        'drills.views.lists.add_irregular_adj_form'),
    (r'^'+listname+'/add-word/add-irregular-verb-form/'+number+'$',
        'drills.views.lists.add_irregular_verb_form'),
    (r'^'+listname+'/add-word/add-irregular-stem/'+number+'$',
        'drills.views.lists.add_irregular_stem'),
    (r'^'+listname+'/add-word/add-irregular-augment/'+number+'$',
        'drills.views.lists.add_irregular_augment'),
    (r'^'+listname+'/add-word/add-no-passive-tense/'+number+'$',
        'drills.views.lists.add_tense_with_no_passive'),
    (r'^'+listname+'/'+word_id+'$',
        'drills.views.lists.single_word'),
    (r'^'+listname+'/'+word_id+'/add-irregular-noun-form/'+number+'$',
        'drills.views.lists.add_irregular_noun_form'),
    (r'^'+listname+'/'+word_id+'/add-irregular-adj-form/'+number+'$',
        'drills.views.lists.add_irregular_adj_form'),
    (r'^'+listname+'/'+word_id+'/add-irregular-verb-form/'+number+'$',
        'drills.views.lists.add_irregular_verb_form'),
    (r'^'+listname+'/'+word_id+'/add-irregular-stem/'+number+'$',
        'drills.views.lists.add_irregular_stem'),
    (r'^'+listname+'/'+word_id+'/add-irregular-augment/'+number+'$',
        'drills.views.lists.add_irregular_augment'),
    (r'^'+listname+'/'+word_id+'/add-no-passive-tense/'+number+'$',
        'drills.views.lists.add_tense_with_no_passive'),

    # Site media
    (r'^site-media/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
    (r'^media/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    # Login stuff
    (r'accounts/login/$', 'django.contrib.auth.views.login', {'template_name':
        'login.html'}),
)

drills/models.py
from django.db import models

from datetime import datetime, timedelta

import random


# Language Models
#################

class Language(models.Model):
    name = models.CharField(max_length=128, unique=True)
    module_name = models.CharField(max_length=128)

    def __unicode__(self):
        return self.name


class Declension(models.Model):
    name = models.CharField(max_length=128)
    language = models.ForeignKey('Language')

    def __unicode__(self):
        return self.name


class DeclinableType(models.Model):
    name = models.CharField(max_length=128)
    language = models.ForeignKey('Language')

    def __unicode__(self):
        return self.name


class Case(models.Model):
    name = models.CharField(max_length=128)
    language = models.ForeignKey('Language')

    def __unicode__(self):
        return self.name


class Number(models.Model):
    name = models.CharField(max_length=128)
    language = models.ForeignKey('Language')

    def __unicode__(self):
        return self.name


class Gender(models.Model):
    name = models.CharField(max_length=128)
    language = models.ForeignKey('Language')

    def __unicode__(self):
        return self.name


class Conjugation(models.Model):
    name = models.CharField(max_length=128)
    language = models.ForeignKey('Language')

    def __unicode__(self):
        return self.name


class Tense(models.Model):
    name = models.CharField(max_length=128)
    language = models.ForeignKey('Language')

    def __unicode__(self):
        return self.name


class Voice(models.Model):
    name = models.CharField(max_length=128)
    language = models.ForeignKey('Language')

    def __unicode__(self):
        return self.name


class Mood(models.Model):
    name = models.CharField(max_length=128)
    language = models.ForeignKey('Language')

    def __unicode__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=128)
    language = models.ForeignKey('Language')

    def __unicode__(self):
        return self.name


# Drilling Models
#################

# We have some redundancy in the way this is set up (i.e., a foreign key that
# could be retrieved by just doing a join on a key that's already present, like
# ConjugationDrillResult pointing to both the verb and the wordlist), but I
# figured that the easier lookups and aggregrations would be worth having a
# little redundancy, because we will be careful to only modify the database in
# valid ways.


class WordList(models.Model):
    user = models.ForeignKey('auth.User')
    name = models.CharField(max_length=128)
    language = models.ForeignKey('Language')

    def __unicode__(self):
        return u'%s: %s' % (self.user.first_name, self.name)


class Tag(models.Model):
    name = models.CharField(max_length=128)
    wordlist = models.ForeignKey('WordList')

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Word(models.Model):
    REVIEW_PERIODS = [
            ('0 minutes', timedelta(0)),
            ('1 minute', timedelta(0, 60)),
            ('10 minutes', timedelta(0, 600)),
            ('1 hour', timedelta(0, 3600)),
            ('5 hours', timedelta(0, 18000)),
            ('1 day', timedelta(1)),
            ('2 days', timedelta(2)),
            ('4 days', timedelta(4)),
            ('1 week', timedelta(7)),
            ('2 weeks', timedelta(14)),
            ('1 month', timedelta(30)),
            ('2 months', timedelta(60)),
            ('4 months', timedelta(120)),
            ('1 year', timedelta(365)),
            ]
    wordlist = models.ForeignKey('WordList')
    word = models.CharField(max_length=128)
    definition = models.CharField(max_length=4096)
    description = models.TextField(blank=True)
    date_entered = models.DateTimeField()
    last_reviewed = models.DateTimeField()
    last_wrong = models.DateTimeField()
    memory_index = models.IntegerField(default=0)
    next_review = models.DateTimeField()
    review_count = models.IntegerField(default=0)
    tags = models.ManyToManyField('Tag')

    def reviewed(self, correct=None):
        now = datetime.now()
        if correct == True:
            time_in_memory = now - self.last_wrong
            time_since_last_seen = now - self.last_reviewed
            if time_in_memory > Word.REVIEW_PERIODS[self.memory_index][1]:
                self.memory_index += 1
            if self.memory_index < len(Word.REVIEW_PERIODS) - 1:
                while (self.memory_index < len(Word.REVIEW_PERIODS) - 1 and
                       time_since_last_seen >
                       Word.REVIEW_PERIODS[self.memory_index][1]):
                    self.memory_index += 1
            else:
                self.memory_index = len(Word.REVIEW_PERIODS) - 1
        elif correct == False:
            self.memory_index = 0
            self.last_wrong = now
        self.last_reviewed = now
        self._set_next_review_date()
        self.review_count += 1
        self.save()
        self.wordlist.user.log.log_vocab_review(self, correct, now)

    def _set_next_review_date(self):
        # This is only called by reviewed(), which calls save(), so we don't
        # call save() at the end of this method.
        delta = Word.REVIEW_PERIODS[self.memory_index][1]
        seconds = 86400 * delta.days + delta.seconds
        new_seconds = seconds * .8 + random.uniform(0, 2) * seconds * .2
        new_days = int(new_seconds / 86400)
        new_seconds = int(new_seconds % 86400)
        self.next_review = datetime.now() + timedelta(new_days, new_seconds)

    def __unicode__(self):
        return u'%s: %s' % (self.wordlist.name, self.word)


# Verb stuff (including irregulars)
###################################

class Verb(models.Model):
    word = models.OneToOneField('Word')
    wordlist = models.ForeignKey('WordList') # duplicate, but speeds things up
    conjugation = models.ForeignKey('Conjugation')


class IrregularVerbForm(models.Model):
    verb = models.ForeignKey('Verb')
    person = models.ForeignKey('Person')
    number = models.ForeignKey('Number')
    tense = models.ForeignKey('Tense')
    mood = models.ForeignKey('Mood')
    voice = models.ForeignKey('Voice')
    form = models.CharField(max_length=128)


class IrregularVerbStem(models.Model):
    verb = models.ForeignKey('Verb')
    tense = models.ForeignKey('Tense')
    mood = models.ForeignKey('Mood')
    voice = models.ForeignKey('Voice')
    stem = models.CharField(max_length=128)


# Maybe this should be in attic_greek/models.py?
class IrregularVerbAugmentedStem(models.Model):
    verb = models.ForeignKey('Verb')
    tense = models.ForeignKey('Tense')
    stem = models.CharField(max_length=128)


class VerbTenseWithNoPassive(models.Model):
    verb = models.ForeignKey('Verb')
    tense = models.ForeignKey('Tense')


# Declension stuff (including irregulars)
#########################################

class DeclinableWord(models.Model):
    word = models.OneToOneField('Word')
    wordlist = models.ForeignKey('WordList') # duplicate, but speeds things up
    declension = models.ForeignKey('Declension')
    type = models.ForeignKey('DeclinableType')

    def __unicode__(self):
        return self.word.word


class IrregularDeclinableForm(models.Model):
    declinable = models.ForeignKey('DeclinableWord')
    gender = models.ForeignKey('Gender')
    number = models.ForeignKey('Number')
    case = models.ForeignKey('Case')
    form = models.CharField(max_length=128)


# Maybe this should be in attic_greek/models.py?
class LongPenult(models.Model):
    declinable = models.OneToOneField('DeclinableWord')


# Drilling statistics
#####################

class Log(models.Model):
    user = models.OneToOneField('auth.User')
    logfile = models.CharField(max_length=256)

    def log(self, string):
        f = open(self.logfile, 'a')
        f.write('%s\n' % string.encode('utf-8'))
        f.close()

    def log_vocab_review(self, word, correct, time):
        log_str = '%s\tWORD_REVIEWED\t' % str(time)
        log_str += 'Wordlist: %s\t' % word.wordlist.name
        log_str += 'Word: %s\t' % word.word
        log_str += 'Word ID: %s\t' % word.id
        log_str += 'Memory Index: %d\t' % word.memory_index
        log_str += 'Correct?: %s\t' % str(correct)
        r = VocabReviewResult(wordlist=word.wordlist, word=word,
                memory_index=word.memory_index, correct=correct, time=time)
        r.save()
        self.log(log_str)

    def log_word_added(self, word, time):
        log_str = '%s\tWORD_ADDED\t' % str(time)
        log_str += 'Wordlist: %s\t' % word.wordlist.name
        log_str += 'Word: %s\t' % word.word
        log_str += 'Definition: %s\t' % word.definition
        log_str += 'Word ID: %s\t' % word.id
        self.log(log_str)


class VocabReviewResult(models.Model):
    wordlist = models.ForeignKey('WordList')
    word = models.ForeignKey('Word')
    memory_index = models.IntegerField()
    correct = models.NullBooleanField()
    time = models.DateTimeField()


class ConjugationDrillResult(models.Model):
    wordlist = models.ForeignKey('WordList')
    verb = models.ForeignKey('Verb')
    conjugation = models.ForeignKey('Conjugation')
    person = models.ForeignKey('Person')
    number = models.ForeignKey('Number')
    tense = models.ForeignKey('Tense')
    mood = models.ForeignKey('Mood')
    voice = models.ForeignKey('Voice')
    correct = models.NullBooleanField()
    date = models.DateTimeField(auto_now_add=True)


class DeclensionDrillResult(models.Model):
    wordlist = models.ForeignKey('WordList')
    word = models.ForeignKey('DeclinableWord')
    type = models.ForeignKey('DeclinableType')
    declension = models.ForeignKey('Declension')
    gender = models.ForeignKey('Gender')
    number = models.ForeignKey('Number')
    case = models.ForeignKey('Case')
    correct = models.NullBooleanField()
    date = models.DateTimeField(auto_now_add=True)


# vim: et sts=4 sw=4

templates/forms/drill_forms.html
{% extends "three_column_base.html" %}

{% load custom_filters %}

{% block above_review %}
<div class="ui-button
    {% ifequal review_type "conjugation" %}
    ui-state-active
    {% endifequal %}
    ui-state-default" id="id_conjugations">
    <a class="ui-button-text" accesskey=c href="conjugations"> Conjugations </a>
</div>
<div class="ui-button
    {% ifequal review_type "declension" %}
    ui-state-active
    {% endifequal %}
    ui-state-default" id="id_declensions">
    <a class="ui-button-text" accesskey=d href="declensions"> Declensions </a>
</div>
{% endblock %}

{% block center_column %}
<div class="review_word">
    <div class="text">
        {{ inflected_form }}
    </div>
</div>
<div class="review_definition">
    <div class="text">
    </div>
</div>
{% endblock %}

{% block left_column %}
<div class="left_review">
    <div class="options">
        Review options coming soon!
    </div>
</div>
{% endblock %}

{% block right_column %}
<div class="tags">
    <div class="filter">
        Filters coming soon!
    </div>
</div>
{% endblock %}

{% block below_review %}
<div class="drill_form_buttons ui-widget-header">
{% block form_options %}
{% endblock %}
    <div>
        <div class="ui-button ui-state-default" id="id_guess_form">
            <a class="ui-button-text" accesskey=g> Guess Form </a>
        </div>
        <div class="ui-button ui-state-default" id="id_new_form">
            <a class="ui-button-text" accesskey=n> New Form </a>
        </div>
    </div>
</div>
{% endblock %}

templates/forms/drill_nouns.html
{% extends "forms/drill_forms.html" %}

{% load custom_filters %}

{% block script_config %}
<script charset="utf-8" type="text/javascript">
    $.fn.review_type = function() {};
    $.fn.review_type.name_ = "declension";
</script>
{% endblock %}

{% block form_options %}
<div>
    <select id="id_gender">
        {% for gender in genders %}
        <option value="{{ gender|variablize }}"> {{ gender }} </option>
        {% endfor %}
    </select>
    <select id="id_number">
        {% for number in numbers %}
        <option value="{{ number|variablize }}"> {{ number }} </option>
        {% endfor %}
    </select>
    <select id="id_case">
        {% for case in cases %}
        <option value="{{ case|variablize }}"> {{ case }} </option>
        {% endfor %}
    </select>
</div>
{% endblock %}

templates/forms/drill_verbs.html
{% extends "forms/drill_forms.html" %}

{% load custom_filters %}

{% block script_config %}
<script charset="utf-8" type="text/javascript">
    $.fn.review_type = function() {};
    $.fn.review_type.name_ = "conjugation";
</script>
{% endblock %}

{% block form_options %}
<div>
    <select id="id_person">
        {% for person in persons %}
        <option value="{{ person|variablize }}"> {{ person }} </option>
        {% endfor %}
    </select>
    <select id="id_number">
        {% for number in numbers %}
        <option value="{{ number|variablize }}"> {{ number }} </option>
        {% endfor %}
    </select>
    <select id="id_tense">
        {% for tense in tenses %}
        <option value="{{ tense|variablize }}"> {{ tense }} </option>
        {% endfor %}
    </select>
    <select id="id_mood">
        {% for mood in moods %}
        <option value="{{ mood|variablize }}"> {{ mood }} </option>
        {% endfor %}
    </select>
    <select id="id_voice">
        {% for voice in voices %}
        <option value="{{ voice|variablize }}"> {{ voice }} </option>
        {% endfor %}
    </select>
</div>
{% endblock %}

templates/forms/table_view.html
{% extends "base.html" %}

{% load custom_filters %}

{% block content %}
<div id="id_table_view">

<select id="id_person">
	{% for person in persons %}
	<option value="{{ person|variablize }}"
	{% ifequal person current_person %}
		selected
	{% endifequal %}
	>
		{{ person }}
	</option>
	{% endfor %}
</select>

<select id="id_number">
	{% for number in numbers %}
	<option value="{{ number|variablize }}"
	{% ifequal number current_number %}
		selected
	{% endifequal %}
	>
		{{ number }}
	</option>
	{% endfor %}
</select>

<div id="id_form_table">
{{ table|safe }}
</div>

See this table for another verb:

<select id="id_verb">
	{% for verb in verbs %}
	<option value="{{ verb.id }}"
	{% ifequal verb.id current_verb.id %}
		selected
	{% endifequal %}>
		{{ verb.word.word }}
	</option>
	{% endfor %}
</select>

</div>
{% endblock %}

templates/forms/view_forms.html
{% extends "base.html" %}

{% load custom_filters %}

{% block content %}
<div class="review">
	<div class="center_review">
		<div class="review_word">
			<div class="text">
				{{ inflected_form }}
			</div>
		</div>
		<div class="drill_form_buttons">
			<table>
				<tr>
					<td>
						Person
						<select id="id_person" class="view_form">
							{% for person in persons %}
							<option value="{{ person|variablize }}">
								{{ person }}
							</option>
							{% endfor %}
						</select>
					</td>
					<td>
						Number
						<select id="id_number" class="view_form">
						{% for number in numbers %}
						<option value="{{ number|variablize }}">
							{{ number }}
						</option>
						{% endfor %}
						</select>
					</td>
					<td>
						Tense
						<select id="id_tense" class="view_form">
						{% for tense in tenses %}
						<option value="{{ tense|variablize }}">
							{{ tense }}
						</option>
						{% endfor %}
						</select>
					</td>
					<td>
						Mood
						<select id="id_mood" class="view_form">
						{% for mood in moods %}
						<option value="{{ mood|variablize }}">
							{{ mood }}
						</option>
						{% endfor %}
						</select>
					</td>
					<td>
						Voice
						<select id="id_voice" class="view_form">
						{% for voice in voices %}
						<option value="{{ voice|variablize }}">
							{{ voice }}
						</option>
						{% endfor %}
						</select>
					</td>
				</tr>
			</table>
		</div>
	</div>
	<div class="right_review">
		<select id="id_verblist" onchange="get_new_verb()">
			{% for v in verbs %}
				<option value="{{ v.id }}"
				{% ifequal v.id verb_id %}selected{% endifequal %}>
				{{ v.word }}
				</option>
			{% endfor %}
		</select>
	</div>
</div>
{% endblock %}